<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="LAPTOP-BIT4U18U" failures="1" tests="1" name="Login Success(failed)" time="11.567" errors="0" timestamp="2025-01-26T20:19:19 IST">
  <testcase classname="pom.demo.tests.LoginTest" name="loginTest" time="5.274">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at pom.demo.assertions.CustomAssertion.validateExpectedContainsInActual(CustomAssertion.java:12)
at pom.demo.tests.LoginTest.loginTest(LoginTest.java:48)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="pom.demo.tests.LoginTest" name="login" time="0.0">
    <ignored/>
  </testcase> <!-- login -->
</testsuite> <!-- Login Success(failed) -->
